# Generated by Django 6.0.2 on 2026-02-27 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(db_index=True, help_text='Unique within the organization.', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='company name')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status', '-created_at'], name='client_org_status_created_idx'), models.Index(fields=['organization', 'email'], name='client_org_email_idx'), models.Index(fields=['organization', 'created_by'], name='client_org_creator_idx'), models.Index(fields=['organization', 'company_name'], name='client_org_company_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'email'), name='unique_client_email_per_org')],
            },
        ),
    ]
