# Generated by Django 6.0.2 on 2026-02-21 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name if omitted.', max_length=255, unique=True, verbose_name='slug')),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], db_index=True, default='FREE', max_length=20, verbose_name='subscription plan')),
                ('seat_limit', models.IntegerField(default=5, help_text='Maximum number of members. -1 = unlimited.', verbose_name='seat limit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='billing email')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='organizatio_slug_d6a03f_idx'), models.Index(fields=['subscription_plan', 'is_active'], name='organizatio_subscri_cbb4cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='invited email')),
                ('role', models.CharField(default='MEMBER', max_length=20, verbose_name='assigned role')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization invite',
                'verbose_name_plural': 'organization invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='organizatio_organiz_c7241c_idx'), models.Index(fields=['email', 'status'], name='organizatio_email_396353_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organization', 'email'), name='unique_pending_invite_per_org_email')],
            },
        ),
    ]
