# Generated by Django 6.0.2 on 2026-02-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_contact_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
