# Generated by Django 6.0.2 on 2026-02-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='task_proj_pri_stat_idx',
            old_name='task_project_active_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='task_proj_prie_stat_idx',
            old_name='task_project_priority_status_idx',
        ),
    ]
