# Generated by Django 6.0.2 on 2026-02-27 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_delete_project'),
        ('projects', '0002_rename_task_project_active_status_idx_task_proj_pri_stat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'position']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_pri_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_prie_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_4f9ca0_idx',
            old_name='project_org_active_status_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_b7735b_idx',
            old_name='project_org_creator_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='projects_pr_user_id_f0db56_idx',
            old_name='membership_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='projects_pr_project_9b2313_idx',
            old_name='membership_project_active_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='projects_ta_organiz_ffee9c_idx',
            old_name='task_org_assignee_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='projects_ta_organiz_82409a_idx',
            old_name='task_org_due_status_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order inside a status column'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEW', 'In Review'), ('DONE', 'Done')], db_index=True, default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'position'], name='projects_ta_project_b4d00b_idx'),
        ),
    ]
